# Generated by Django 6.0.4 on 2026-04-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(max_length=500)),
                ('date_of_addm', models.DateField()),
                ('date_of_discharge', models.DateField()),
                ('room_type', models.CharField(choices=[('COMMON WARD', 'common ward'), ('SEMI-PRIVATE', 'semi-private'), ('PRIVATE AC', 'private ac'), ('PRIVATE NON-AC', 'private non-ac'), ('DELUXE', 'deluxe')], max_length=100)),
                ('food_required', models.BooleanField()),
                ('total_days', models.PositiveIntegerField()),
                ('Patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.userdetails')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorsdetails')),
                ('treatment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.treatments')),
            ],
        ),
    ]
