# Generated by Django 6.0.4 on 2026-04-13 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('learnapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('years_of_experiance', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.CharField(choices=[('CBC', 'cbc'), ('LFT', 'lft'), ('URINE TOTAL TEST', 'urine total test'), ('URINE MICROSCOPIC', 'urine microscopic'), ('SERUM ROUTINE', 'serum routine'), ('THYROID', 'thyroid')], max_length=100)),
                ('lab_result', models.CharField(choices=[('PENDING', 'pending'), ('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_range', models.CharField(choices=[('NILL', 'nill'), ('POSITIVE', 'positive'), ('NEGETIVE', 'negetive'), ('NORMAL', 'normal'), ('ABNORMAL', 'abnormal')], max_length=100)),
                ('result_desc', models.TextField()),
                ('test_cost', models.IntegerField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.userdetails')),
                ('reffered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorsdetails')),
            ],
        ),
    ]
