# Generated by Django 6.0.4 on 2026-04-13 06:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('specs', models.CharField(choices=[('general medicine', 'GENERAL MEDICINE'), ('cardiologist', 'CARDIOLOGIST'), ('ent', 'ENT'), ('orthopedic', 'ORTHOPEDIC'), ('eye specialist', 'EYE SPECIALIST'), ('dentist', 'DENTIST'), ('others', 'OTHERS')], max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
                ('mail', models.EmailField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('docpic', models.ImageField(blank=True, null=True, upload_to='doctorimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('catogery', models.CharField(choices=[('general medicine', 'GENERAL MEDICINE'), ('cardiologist', 'CARDIOLOGIST'), ('ent', 'ENT'), ('orthopedic', 'ORTHOPEDIC'), ('eye specialist', 'EYE SPECIALIST'), ('dentist', 'DENTIST'), ('others', 'OTHERS')], max_length=100)),
                ('description', models.TextField()),
                ('doctorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('fee', models.PositiveIntegerField(default=500)),
                ('patient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('time', models.CharField(choices=[('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM')])),
                ('problem', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorsdetails')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.treatments')),
            ],
        ),
    ]
